'use strict';
/* ================= LANG_HE — HEBREW DICTIONARY =================
   Keys are the EXACT English display strings used in index.html / js (see js/i18n.js).
   Register: native gamer Hebrew — status = present-plural (מתחברים…), player = neutral-spelling 2sg past (שרדת).
   Edit freely — a missing entry falls back to English. Live tweak: debugLang('English key','עברית') in the console (see i18n.js). */
const LANG_HE={
/* --- start menu --- */
'Survive the swarm. Your gun auto-fires — you just move, dodge, and choose upgrades. Unlock homing missiles, an orbiting shield, and chain lightning. How long can you last?':'שרדו את הנחיל. הנשק יורה לבד — אתם רק זזים, מתחמקים ובוחרים שדרוגים. תפתחו טילים מתביתים, מגן מקיף וברק משתרשר. כמה זמן תחזיקו?',
'WASD / ↑↓←→ move':'WASD / →←↓↑ תנועה',
'auto-fire':'ירי אוטומטי',
'P / Esc pause':'P / Esc השהיה',
'M mute':'M השתקה',
'P / Esc resume':'P / Esc המשך',
'EASY':'קל','NORMAL':'רגיל','HARD':'קשה',
'Easy':'קל','Normal':'רגיל','Hard':'קשה',
'balanced — recommended for a first run':'מאוזן — מומלץ לריצה ראשונה',
'▶ PLAY':'▶ התחל',
'📱 Get the Android app (APK)':'📱 הורדת אפליקציית אנדרואיד (APK)',
'⚡ Pickups — found on the map':'⚡ איסופים — פזורים על המפה',
'🛠 Weapons — unlocked on level-up':'🛠 נשקים — נפתחים בעליית רמה',
'🔀 Weapon merges — pair upgrades to evolve':'🔀 מיזוגי נשק — צמדי שדרוגים שמתמזגים',
'🗺 Boss rewards — choose one of three':'🗺 פרסי בוס — בחרו אחד משלושה',
'🌐 Global best runs':'🌐 שיאי העולם',
'🏅 Achievements':'🏅 הישגים',
'🎨 Showcase — skins & soundtrack':'🎨 תצוגה — סקינים ופסקול',
'Skins':'סקינים','Trails':'שבילים','Soundtrack':'פסקול','Grids':'רשתות',
/* --- HUD --- */
'SCORE':'ניקוד','WAVE':'גל','MODE':'מצב','TIME':'זמן','LVL':'רמה',
'🔊 sound':'🔊 צליל',
'📳 vibrate':'📳 רטט','📴 vibrate':'📴 רטט',
'CLEARED':'השטח נקי',
'arena breather — spawns throttled':'הפוגה — הנחיל נרגע לרגע',
/* --- boot / auth --- */
'Connecting':'מתחברים',
'GRID ACCESS':'גישה לרשת',
'Link up to carry your callsign, achievements and best runs across every device.':'מתחברים פעם אחת — והכינוי, ההישגים והשיאים שלך זמינים בכל מכשיר.',
'email':'אימייל',
'password (min 6)':'סיסמה (לפחות 6 תווים)',
'6-digit code':'קוד בן 6 ספרות',
'callsign (3–16)':'כינוי (3–16)',
'✔ JACK IN':'✔ מתחברים',
'📧 Send me an access code':'📧 שלחו לי קוד גישה',
'New operator? Register':'מפעילים חדשים? הירשמו',
/* --- game over --- */
'GAME OVER':'המשחק נגמר',
'you scored':'צברת',
'↻ PLAY AGAIN':'↻ שחקו שוב',
'↩ main menu':'↩ תפריט ראשי',
/* --- level up / boss reward --- */
'LEVEL UP':'עלית רמה!',
'choose one upgrade':'בוחרים שדרוג אחד',
'BOSS DOWN — CHOOSE YOUR REWARD':'הבוס נפל — בוחרים פרס',
'pick one of three · two are safe, one is a risky gamble':'אחד משלושה · שניים בטוחים, אחד הימור מסוכן',
/* --- pause --- */
'PAUSED':'מושהה',
'your build':'הבילד שלך',
'weapon merges — evolved upgrades':'מיזוגי נשק — שדרוגים שהתמזגו',
'combat stats':'נתוני קרב',
'▶ RESUME':'▶ ממשיכים',
'✕ Quit to main menu':'✕ ניתוק מהרשת',
'⚠ <b>End this run?</b> Quitting now <b>permanently loses all progress</b> from this game — your score, level, upgrades, weapons and time will be gone. This cannot be undone.':'⚠ <b>לנתק באמצע ריצה?</b> כל מה שהשגת — ניקוד, רמה, שדרוגים, נשקים וזמן — <b>יימחק לתמיד</b>. אין דרך חזרה.',
'Yes, end run & lose progress':'כן, לנתק ולאבד הכול',
'No, keep playing':'לא, חוזרים לקרב',
/* --- upgrades (names + card label fragments) --- */
'Sharper Rounds':'קליעים חדים','Rapid Fire':'ירי מהיר','Split Shot':'ירי מפוצל','Piercing':'חדירה',
'Swift Boots':'מגפי זריזות','Vitality':'חיוניות','Magnet Core':'ליבת מגנט','Regeneration':'התחדשות',
'Lifesteal':'שאיבת חיים','Hyper Velocity':'מהירות-על','Homing Missiles':'טילים מתביתים',
'Orbiting Shield':'מגן מקיף','Chain Lightning':'ברק משתרשר',
'bullet damage':'נזק קליעים','fire rate':'קצב ירי','Fires':'יורה','projectiles per volley':'קליעים בכל מטח',
'Bullets pass through':'הקליעים חודרים דרך','enemy':'אויב אחד','enemies':'אויבים','move speed':'מהירות תנועה',
'max HP &amp; heal 30':'חיים מרביים + ריפוי 30','XP pickup range':'טווח איסוף XP','HP / sec':'חיים / שנייה',
'Heal':'ריפוי','HP on every kill':'חיים על כל הרג','bullet speed':'מהירות קליע','damage':'נזק',
'Launch a homing missile that seeks &amp; explodes (AoE)':'משגר טיל מתביית שרודף ומתפוצץ (נזק שטח)',
'faster salvos (AoE)':'מטחים מהירים יותר (נזק שטח)',
'guardian orbs circle you, shredding contact':'כדורי מגן חגים סביבכם וגורסים כל מגע',
'Periodic bolt that arcs between enemies':'ברק תקופתי שמקפץ בין אויבים','faster, arcs more':'מהיר יותר, מקפץ יותר',
'Lv':'רמה','NEW':'חדש','EVOLVE':'אבולוציה','EVOLVED':'שודרג','COMING ONLINE':'עולה לרשת','⚡EVO':'⚡משודרג','Pair':'שלבו',
/* --- weapon merges (synergies) --- */
'CLUSTER WARHEADS':'ראשי נפץ מתפצלים','missiles fragment into a shrapnel burst on impact':'טילים מתפצלים לרסס רסיסים בפגיעה',
'TESLA WEB':'רשת טסלה','lightning forks farther and arcs through far more foes':'הברק מתפצל רחוק יותר ומקפץ דרך הרבה יותר אויבים',
'AEGIS DRIVE':'מגן איגיס','guardian orbs swell, multiply, and knock enemies back':'כדורי המגן גדלים, מתרבים והודפים אויבים לאחור',
'RAILGUN':'תותח מסילה','shots become a hyper-velocity infinite-pierce lance':'הירי הופך לרומח במהירות-על שחודר הכול',
'CRIMSON STORM':'סופה ארגמנית','lifesteal procs on EVERY kill — the cooldown is gone':'שאיבת חיים פועלת על כל הרג — בלי זמן המתנה',
/* --- boss rewards (map nodes) --- */
'FREE UPGRADE':'שדרוג חינם','Safe · pick any one upgrade now — like an extra level-up.':'בטוח · בוחרים שדרוג אחד עכשיו — כמו עליית רמה נוספת.',
'LOOT DROP':'שלל','Safe · two power-ups (heal / nuke / magnet / overdrive) drop at your feet.':'בטוח · שני חיזוקים (ריפוי / פצצה / מגנט / טורבו) נופלים לרגליכם.',
'ELITE FIGHT':'קרב עילית','Risky · a tough elite pack spawns — kill it for a guaranteed power-up.':'מסוכן · חבורת עילית קשוחה מגיחה — חסלו אותה לחיזוק מובטח.',
/* --- pickups --- */
'+25 HP':'+25 חיים','NUKE':'פצצה','NUKE!':'בום!','XP RUSH':'גל XP','XP RUSH x2':'XP כפול x2','OVERDRIVE':'טורבו',
'Nuke':'פצצה','XP Rush':'גל XP','Overdrive':'טורבו',
'Instantly restores 25 HP. Grab it when you\'re hurt.':'מחזיר מיד 25 נקודות חיים. קחו כשנפגעתם.',
'Detonates the whole screen — clears a swarm in a pinch.':'מפוצץ את כל המסך — מנקה נחיל ברגע צרה.',
'Pulls in every XP orb on the map for an instant level-up.':'מושך כל כדור XP במפה לעליית רמה מיידית.',
'9 seconds of double fire-rate and +60% damage. Go aggressive.':'9 שניות של קצב ירי כפול ו‑60%+ נזק. תקפו בלי רחמים.',
'Auto-launches a seeking missile that explodes for area damage.':'משגר אוטומטית טיל מתביית שמתפוצץ לנזק שטח.',
'Orbs spin around you, destroying anything they touch — strong defense.':'כדורים חגים סביבכם ומשמידים כל מה שהם נוגעים בו — הגנה חזקה.',
'A bolt that leaps between nearby enemies, hitting several at once.':'ברק שמזנק בין אויבים קרובים ופוגע בכמה בבת אחת.',
'appeared on the map':'הופיע על המפה','(boss drop)':'(שלל בוס)',
/* --- bosses --- */
'BOSS':'בוס','BOSS DOWN':'הבוס נפל','REVENANT':'רוונאנט','MAELSTROM':'מלשטרום','OVERSEER':'המשגיח',
/* --- loadout pips --- */
'Missiles':'טילים','Shield':'מגן','Lightning':'ברק',
/* --- pause stats --- */
'survived':'שרדת','score':'ניקוד','kills':'הריגות','wave':'גל','level':'רמה','health':'חיים',
'on screen':'על המסך','score / s':'ניקוד / שנ׳','sustain':'תחזוקה','on':'פעיל',
'no upgrades yet — collect XP orbs to level up':'עוד אין שדרוגים — אוספים XP ועולים רמה',
'none yet — pair the right upgrades to merge a weapon (see 🔀 Weapon merges on the menu)':'עוד אין — משלבים את השדרוגים הנכונים וממזגים נשק (🔀 מיזוגי נשק בתפריט)',
'🗡️ Damage':'🗡️ נזק','⚡ Fire rate':'⚡ קצב ירי','🔱 Projectiles':'🔱 קליעים','➶ Pierce':'➶ חדירה',
'➹ Bullet spd':'➹ מהירות קליע','🥾 Move spd':'🥾 מהירות תנועה','❤️ Max HP':'❤️ חיים מרביים','🧲 Magnet':'🧲 מגנט',
'✚ Regen':'✚ התחדשות','🩸 Lifesteal':'🩸 שאיבת חיים','🚀 Missiles':'🚀 טילים','🛡️ Shield':'🛡️ מגן','🌩️ Lightning':'🌩️ ברק',
'/s':'/שנ׳','/kill':'/הרג',
/* --- game over / hud misc --- */
'★ NEW BEST!':'★ שיא חדש!','best:':'השיא:','🔇 muted':'🔇 מושתק',
/* --- difficulty hints --- */
'Relaxed — slower spawns and weaker enemies. Good for learning the ropes.':'רגוע — הגחות איטיות ואויבים חלשים. טוב ללימוד הבסיס.',
'Balanced pace and pressure. Recommended for your first real run.':'קצב ולחץ מאוזנים. מומלץ לריצה האמיתית הראשונה.',
'Brutal — dense swarms, tanky enemies and heavy hits. For veterans.':'אכזרי — נחילים צפופים, אויבים משוריינים ומכות כבדות. לוותיקים.',
/* --- leaderboard --- */
'Global board offline.<br>Scores still save on this device.':'הלוח העולמי לא זמין.<br>הניקוד עדיין נשמר במכשיר הזה.',
'No runs yet.<br>Be the first!':'הלוח עוד ריק.<br>ההזדמנות שלך.',
'Global board offline — your score is saved on this device.':'הלוח העולמי לא זמין — הניקוד נשמר במכשיר הזה.',
'Good job! You made it to the leaderboard!':'כבוד! נכנסת ללוח העולמי!',
'You were':'עוד','points away from the leaderboard.':'נקודות והיית בלוח העולמי.',
/* --- ONLINE/OFFLINE identity badge (menu #netstatus + death-screen #gonet) --- */
'ONLINE — logged in as':'מחובר — מזוהה כ',
'ONLINE':'מחובר',
'OFFLINE — this device only':'לא מקוון — במכשיר זה בלבד',
'Your runs post to the global leaderboard.':'הריצות שלך נרשמות בטבלת השיאים העולמית.',
'No connection — runs are saved here but won’t reach the leaderboard.':'אין חיבור — הריצות נשמרות כאן אך לא יגיעו לטבלת השיאים.',
/* --- achievements UI chrome --- */
'All':'הכול','Combat':'קרב','Boss':'בוסים','Skill':'מיומנות','Speed':'מהירות','Challenge':'אתגר','Secret':'סודי',
'HIDDEN':'מוסתר','UNLOCKED':'נפתח','LOCKED':'נעול',
'bronze':'ארד','silver':'כסף','gold':'זהב','BRONZE':'ארד','SILVER':'כסף','GOLD':'זהב',
'Hidden — unlock to reveal.':'מוסתר — פתחו כדי לחשוף.',
'Nothing here yet in this category.':'אין כאן עדיין כלום בקטגוריה הזו.',
'No achievements unlocked yet — go play a run!':'עוד לא נפתחו הישגים — צאו לריצה!',
'ACHIEVEMENT UNLOCKED':'הישג נפתח','🎨 COSMETIC UNLOCKED':'🎨 קוסמטיקה נפתחה',
'Skin':'סקין','Trail':'שביל','Survival':'הישרדות',
/* --- achievement titles + descriptions --- */
'Draw First Blood':'דם ראשון','Get your first kill.':'השיגו את ההרג הראשון שלכם.',
'Swarm Breaker':'שובר נחילים','Kill 100 enemies in a single run.':'חסלו 100 אויבים בריצה אחת.',
'One-Man Army':'צבא של איש אחד','Kill 500 enemies in a single run.':'חסלו 500 אויבים בריצה אחת.',
'Annihilator':'המכחיד','Kill 1,000 enemies in a single run.':'חסלו 1,000 אויבים בריצה אחת.',
'High Scorer':'שיאן','Score 10,000 in a single run.':'צברו 10,000 נקודות בריצה אחת.',
'Score Legend':'אגדת ניקוד','Score 50,000 in a single run.':'צברו 50,000 נקודות בריצה אחת.',
'Neon God':'אל הניאון','Score 100,000 in a single run.':'צברו 100,000 נקודות בריצה אחת.',
'Wave Rider':'רוכב הגלים','Reach wave 10.':'הגיעו לגל 10.',
'Wave Master':'אדון הגלים','Reach wave 20.':'הגיעו לגל 20.',
'Abyss Walker':'הולך התהום','Reach wave 30.':'הגיעו לגל 30.',
'Boss Slayer':'קוטל בוסים','Defeat your first boss.':'הביסו את הבוס הראשון שלכם.',
'Boss Hunter':'צייד בוסים','Defeat 10 bosses (lifetime).':'הביסו 10 בוסים (מצטבר).',
'Apex Predator':'טורף-על','Defeat 50 bosses (lifetime).':'הביסו 50 בוסים (מצטבר).',
'Power Surge':'נחשול כוח','Reach level 10 in a single run.':'הגיעו לרמה 10 בריצה אחת.',
'Ascended':'התעלות','Reach level 25 in a single run.':'הגיעו לרמה 25 בריצה אחת.',
'Veteran':'ותיק','Finish 10 runs (lifetime).':'סיימו 10 ריצות (מצטבר).',
'Hardcore':'הארדקור','Reach wave 10 on Hard.':'הגיעו לגל 10 ברמת קושי קשה.',
'Ghost in the Grid':'רוח רפאים ברשת','Reach wave 10 without taking a single hit.':'הגיעו לגל 10 בלי לספוג ולו פגיעה אחת.',
'Untouchable':'חסין','Reach wave 20 without taking a single hit.':'הגיעו לגל 20 בלי לספוג ולו פגיעה אחת.',
'Flawless Protocol':'פרוטוקול מושלם','Destroy a boss without taking a hit in the fight.':'השמידו בוס בלי לספוג פגיעה בקרב.',
'Factory Settings':'הגדרות יצרן','Reach wave 15 using only the starting gun.':'הגיעו לגל 15 עם רובה הפתיחה בלבד.',
'Overclocked':'האצת יתר','Wield all three weapons at once and reach wave 15.':'החזיקו בשלושת כלי הנשק בו-זמנית והגיעו לגל 15.',
'Second Wind':'רוח שנייה','Survive into a new wave after dropping below 10% HP.':'שרדו עד גל חדש אחרי שירדתם מתחת ל‑10% חיים.',
'Glass Cannon':'תותח זכוכית','Reach wave 12 without ever raising max HP.':'הגיעו לגל 12 בלי להעלות חיים מרביים אף פעם.',
'Power Spike':'זינוק כוח','Reach level 10 within 90 seconds.':'הגיעו לרמה 10 תוך 90 שניות.',
'Ascendant Rush':'דהרת התעלות','Reach level 20 within 5 minutes.':'הגיעו לרמה 20 תוך 5 דקות.',
'Blitz':'בליץ','Reach wave 10 within 4 minutes.':'הגיעו לגל 10 תוך 4 דקות.',
'Killer Instinct':'אינסטינקט רצחני','Destroy a boss within 15s of its spawn.':'השמידו בוס תוך 15 שניות מהופעתו.',
'Massacre Clock':'שעון הטבח','Get 250 kills in the first 3 minutes.':'השיגו 250 הריגות ב‑3 הדקות הראשונות.',
'Conscientious Objector':'סרבן מצפוני','Reach wave 8 while still at level 1.':'הגיעו לגל 8 בעודכם ברמה 1.',
'Pacifist Protocol':'פרוטוקול פציפיסטי','Survive 5 minutes with fewer than 25 kills.':'שרדו 5 דקות עם פחות מ‑25 הריגות.',
'Minimalist':'מינימליסט','Reach wave 12 owning at most one weapon.':'הגיעו לגל 12 עם נשק אחד לכל היותר.',
'Ascetic':'סגפן','Reach wave 10 collecting zero pickups.':'הגיעו לגל 10 בלי לאסוף אף חיזוק.',
'Bare Bones':'עצמות חשופות','Reach wave 20 wielding only your starter weapon.':'הגיעו לגל 20 עם נשק הפתיחה בלבד.',
'Any% Speedrun':'ספידראן Any%','Die within 5 seconds of starting a run.':'מותו תוך 5 שניות מתחילת הריצה.',
'Leet':'ליט','Finish a run with exactly 1,337 kills.':'סיימו ריצה עם 1,337 הריגות בדיוק.',
'The Completionist’s Curse':'קללת המשלים','Unlock 80% of every other achievement.':'פתחו 80% מכל שאר ההישגים.',
/* --- reward toasts + showcase galleries --- */
'🎵 SOUNDTRACK UNLOCKED':'🎵 פסקול נפתח','🌌 GRID THEME UNLOCKED':'🌌 ערכת רשת נפתחה',
'🎨 TRAIL UNLOCKED':'🎨 שביל נפתח','🎨 SKIN UNLOCKED':'🎨 סקין נפתח',
'🎵 TRACK EQUIPPED':'🎵 רצועה הופעלה','🌌 GRID EQUIPPED':'🌌 רשת הופעלה','🎨 TRAIL EQUIPPED':'🎨 שביל הופעל',
'Unlocked':'נפתחו','Owned':'ברשותך','▶ Preview':'▶ האזנה','✓ EQUIPPED':'✓ מופעל','EQUIP':'הפעלה',
'from:':'מתוך:','locked':'נעול','track':'רצועה','grid':'רשת','trail':'שביל','skin':'סקין',
'Orchestral score':'פסקול תזמורתי','Achievement reward':'פרס הישג','Map colour theme':'ערכת צבעים למפה',
'Orchestral':'תזמורתי','Unlock:':'לפתיחה:',
'Projectile trail':'שביל קליעים','Stock neon hull':'גוף הניאון המקורי','Hull cosmetic':'קוסמטיקת גוף',
'Gold-tier reward':'פרס דרגת זהב','Cosmic Nebula':'ערפילית קוסמית','No Trail':'בלי שביל','Default Hull':'גוף ברירת מחדל',
'Pop':'פופ','Rap':'ראפ','Classical':'קלאסי','Metal':'מטאל','Acoustic':'אקוסטי','Music Sync':'סנכרון מוזיקלי',
/* --- Total Genre Conversion: Warden titles + Full Sync retheme toast --- */
'WARDEN PROTOCOL':'פרוטוקול השומר','MIDNIGHT SET':'סט של חצות','HEADLINER':'כוכב ראשי','MAIN STAGE':'הבמה הראשית','FINAL VERSE':'הבית האחרון','GRAND RECITAL':'רסיטל גדול',
'⚡ FULL SYNC':'⚡ סנכרון מלא','grid conversion':'המרת רשת',
/* --- cosmetic / track titles --- */
'First Blood Spark':'ניצוץ דם ראשון','Swarm Pulse':'פעימת נחיל','Legionnaire':'לגיונר','Crimson Husk':'קליפה ארגמנית',
'Aurora Drift':'סחף זוהר','Regent':'עוצר','Neon God Trail':'שביל אל הניאון','Midnight Jazz':'ג׳אז של חצות',
'Maelstrom Waltz':'ואלס המערבולת','Void Warden':'שומר התהום','Surge Arc':'קשת מתח','Violet Void':'תהום סגולה',
'Neon Pop':'ניאון פופ','Cinder Frame':'שלד גחלים','Crimson Nebula':'ערפילית ארגמן','Requiem of the Hunt':'רקוויאם הציד',
'Warden Halo':'הילת השומר','Ghost Streak':'פס רפאים','Phase Trail':'שביל פאזה','Warden’s Bane':'חורבן השומר',
'Factory Line':'קו ייצור','Overclock Toccata':'טוקטת האצה','Second Wind Gust':'משב רוח שנייה','Prism Shard':'רסיס מנסרה',
'Spike Trail':'שביל דוקרן','Blitz Streak':'פס בזק','Predator':'טורף','Breakbeat':'ברייקביט',
'Objector Halo':'הילת הסרבן','Radiant Aura':'הילה זוהרת','Monoline':'קו יחיד','Ascetic Nocturne':'נוקטורן סגפני',
'Acoustic Grid':'רשת אקוסטית','Any% Blip':'בליפ Any%','1337 Chrome':'כרום 1337','Prism Core':'ליבת מנסרה',
/* --- GRID ACCESS auth stages --- */
'NEW OPERATOR':'מפעיל חדש','VERIFY UPLINK':'אימות ערוץ','CHOOSE CALLSIGN':'בחרו כינוי',
'Set a password, then confirm with the 6-digit code we uplink to your email.':'בוחרים סיסמה ומאשרים עם הקוד בן 6 הספרות שיישלח לאימייל שלך.',
'Enter the 6-digit code sent to':'הזינו את הקוד בן 6 הספרות שנשלח אל',
'to bring your operator online.':'כדי להעלות את המפעיל שלך לרשת.',
'Enter the 6-digit access code uplinked to':'הזינו את קוד הגישה בן 6 הספרות שנשלח אל',
'✔ REGISTER':'✔ הרשמה','✔ CONFIRM & ENTER':'✔ אשרו והיכנסו','✔ VERIFY CODE':'✔ אימות קוד',
'✔ ENTER THE GRID':'✔ כניסה לרשת','✔ OK':'✔ אישור',
'↻ Resend code':'↻ שליחת קוד מחדש','← Back':'← חזרה','← Use password':'← כניסה עם סיסמה',
'Already on the grid? Sign in':'כבר ברשת? התחברו',
'Your handle on the global grid. 3–16 characters.':'הכינוי שלך ברשת העולמית. 3–16 תווים.',
'SYSTEM ACCESS DENIED: RESTRICTED CALLSIGN':'הכינוי הזה חסום — נסו משהו אחר',
'Please use at least 3 characters.':'קצר מדי — לפחות 3 תווים.',
'Claiming callsign…':'תופסים את הכינוי…','CALLSIGN ALREADY CLAIMED':'הכינוי תפוס — מישהו הקדים אותך',
'Couldn’t save the callsign — try again.':'שמירת הכינוי נכשלה — נסו שוב.',
'Grid unreachable — try again.':'הרשת לא זמינה — נסו שוב.','Uplink failed — try again.':'השידור נכשל — נסו שוב.',
'Enter the 6-digit code.':'צריך את הקוד בן 6 הספרות.','Verifying…':'בודקים את הקוד…',
'Enter a valid email address.':'האימייל לא נראה תקין — בדקו שוב.',
'Password must be at least 6 characters.':'סיסמה קצרה מדי — לפחות 6 תווים.',
'Offline — can’t reach the grid right now.':'אין חיבור — אי אפשר להגיע לרשת כרגע.',
'Callsign: at least 3 characters.':'כינוי קצר מדי — לפחות 3 תווים.',
'Creating account…':'פותחים חשבון…','Signing in…':'נכנסים…',
'Enter your email above first.':'קודם ממלאים אימייל למעלה.',
'Offline — can’t email a code right now.':'אין חיבור — אי אפשר לשלוח קוד כרגע.',
'Sending code…':'שולחים קוד…','Resending…':'שולחים שוב…',
/* --- weaponsmith (merged from main) --- */
'Weaponsmith':'נפח נשק','Evolve a weapon by completing an upgrade pair.':'מזגו נשק על ידי השלמת צמד שדרוגים.',
'Evolver Arc':'קשת המיזוג',
};
I18N.apply();
